[package]
name = "better_neural_net_cli"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib/mod.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
better_neural_net_core = { path = "../core" }
byteorder = "1.5.0"
find_folder = "0.3.0"
indicatif = "0.17.11"
